export const PLAYER_MOVED = 'PLAYER_MOVED';
export const PLAYER_SCORED = 'PLAYER_SCORED';

export const SESSION_STARTED = 'SESSION_STARTED';
export const SESSION_MAZE_ARRIVAL = 'SESSION_MAZE_ARRIVAL';
