export const PLAYER_MOVED = 'PLAYER_MOVED';
export const PLAYER_SCORED = 'PLAYER_SCORED';
export const PLAYER_UPDATE = 'PLAYER_UPDATE';

export const SESSION_STARTED = 'SESSION_STARTED';
export const SESSION_MAZE_ARRIVAL = 'SESSION_MAZE_ARRIVAL';
export const SESSION_CONNECTION_STATUS = 'SESSION_CONNECTION_STATUS';
export const SESSION_STATE_CHANGE = 'SESSION_STATE_CHANGE';
export const SESSION_HEART_BEAT_STATE_CHANGE = 'SESSION_HEART_BEAT_STATE_CHANGE';
export const SESSION_INIT_CONNECTION = 'SESSION_INIT_CONNECTION';
export const SESSION_CHANGE_USERNAME = 'SESSION_CHANGE_USERNAME';

export const UI_SET_OVERLAY = 'UI_SET_OVERLAY';

export const PLAYERS_UPDATE = 'PLAYERS_UPDATE';

